### ISSUE TITLE
Investigate using the RuntimeTypeAdapterFactory

### ISSUE THREAD

**Issue by lachlanm** [lachlanm/gsonpath#9]
The Gson project has a class called RuntimeTypeAdapterFactory (found at - https://github.com/google/gson/blob/master/extras/src/main/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactory.java) which can solve some polymorphism challenges.

It would be interesting to generate this factory (or something very similar) using annotations.

**Comment by lachlanm** [comment]
Sample code has been added to gsonpath-sample module.

There is no real benefit to adding an annotation for this, as it compliments the current annotations nicely.

**Comment by GediminasZukas** [comment]
Is it necessary to write ```getSubType``` function by hand in order to make polymorphic serialization work? https://github.com/LachlanMcKee/gsonpath/blob/master/sample/src/main/java/gsonpath/kotlin/SealedClassSampleWithArray.kt#L17

Maybe ```RuntimeTypeAdapterFactory``` based solution could allow to handle polymorphic serialization with few annotations only and without any other hand written code? Like for example ```kotlinx-serialization``` does: https://medium.com/@andreclassen1337/goodbye-runtimetypeadapterfactory-polymorphic-serialization-using-kotlinx-serialization-46a8cec36fdc
